version: "3.1"
services:

    redis:
      image: redis:alpine
      container_name: weatherinfo-redis

    postgres:
      image: postgres:9.6-alpine
      container_name: weatherinfo-postgres
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=toor
        - POSTGRES_DB=weatherInfo

    webserver:
      image: nginx:alpine
      container_name: weatherinfo-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"

    php-fpm:
      build: phpdocker/php-fpm
      environment:
        XDEBUG_CONFIG: remote_host=172.18.0.1 remote_port=9001 idekey=PHPSTORM remote_enable=On
        PHP_IDE_CONFIG: "serverName=http://weatherinfo.local"
      container_name: weatherinfo-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

#    hoverfly:
#      image: spectolabs/hoverfly:latest
#      container_name: weatherinfo-hoverfly
#      ports:
#        - "8888:8888"
#        - "8500:8500"

    mountebank:
      image: jkris/mountebank:latest
      container_name: weatherinfo-mountebank
      volumes:
      - ./tests/mountebank/imposters:/imposters
      command: --configfile /imposters/imposters.ejs --allowInjection --loglevel debug
      ports:
      - "2525:2525"
      - "9090:9090"